#!/usr/bin/env python3
"""Build blog post pages from markdown.

Write a post in `blogposts/<anything>.md`, run this script, and it renders
`blog-<slug>.html` from `blogposts/_template.html` and refreshes the card list
in `blog.html`.

Usage:
    python3 scripts/build_blog.py              # build every post
    python3 scripts/build_blog.py blogposts/foo.md   # build just one

Markdown files may start with a front matter block:

    ---
    title: Train your moral imagination, reach for the sublime.
    short_title: Train your moral imagination   # used on the blog index card
    date: 2026-07-02
    slug: train-your-moral-imagination          # -> blog-train-your-moral-imagination.html
    description: One line for search engines and link previews.
    keywords: comma, separated, keywords
    card_image: images/bandida_se_escapo.JPEG
    blurb: Optional one-liner shown under the title on the blog index.
    hero: images/foo.jpg                        # optional image above the text
    hero_alt: Describe the image
    draft: true                                 # skip this post
    images:                                     # map Google Docs image refs
      image1: images/bandida_se_escapo.JPEG     #   to files already in images/
    ---

Anything not given is inferred: the title from the first `# heading`, the date
from a `## 02.07.2026` line just under it, the slug from the title.

Google Docs export notes: images come out as base64 blobs. Any blob not mapped
under `images:` is written out to `images/<slug>-<ref>.<ext>` automatically.
A line of `***` becomes a typographic scene break.
"""

import base64
import html
import os
import re
import sys
from datetime import date, datetime

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
POSTS_DIR = os.path.join(ROOT, "blogposts")
IMAGES_DIR = os.path.join(ROOT, "images")
TEMPLATE = os.path.join(POSTS_DIR, "_template.html")
INDEX = os.path.join(ROOT, "blog.html")
SITE_URL = "https://agathaduzan.com"

POSTS_START = "<!-- BLOG_POSTS:START (generated by scripts/build_blog.py) -->"
POSTS_END = "<!-- BLOG_POSTS:END -->"

try:
    import markdown
except ImportError:
    sys.exit("Missing dependency: pip install markdown")


# --------------------------------------------------------------------------
# front matter
# --------------------------------------------------------------------------

def parse_front_matter(text):
    """Return (meta, body). Supports `key: value` and one level of nesting."""
    if not text.startswith("---"):
        return {}, text
    end = re.search(r"^---\s*$", text[3:], re.M)
    if not end:
        return {}, text
    raw = text[3:3 + end.start()]
    body = text[3 + end.end():].lstrip("\n")

    meta, current = {}, None
    for line in raw.splitlines():
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        indented = line[0] in " \t"
        key, _, value = line.strip().partition(":")
        key, value = key.strip(), value.strip().strip('"').strip("'")
        if indented and current is not None:
            meta[current][key] = value
        elif value == "":
            current = key
            meta[key] = {}
        else:
            current = None
            meta[key] = value
    return meta, body


def truthy(value):
    return str(value).strip().lower() in ("1", "true", "yes", "on")


def slugify(text):
    text = re.sub(r"[^\w\s-]", "", text.lower())
    return re.sub(r"[\s_-]+", "-", text).strip("-")


def parse_date(value):
    for fmt in ("%Y-%m-%d", "%d.%m.%Y", "%d/%m/%Y", "%Y/%m/%d"):
        try:
            return datetime.strptime(value.strip(), fmt).date()
        except ValueError:
            continue
    return None


# --------------------------------------------------------------------------
# markdown preprocessing
# --------------------------------------------------------------------------

DATA_URI_DEF = re.compile(
    r"^\[([^\]]+)\]:\s*<?\s*data:image/([\w.+-]+);base64,([A-Za-z0-9+/=\s]+?)\s*>?\s*$",
    re.M,
)
EXT_FIX = {"jpeg": "jpg", "svg+xml": "svg"}


def extract_images(body, slug, mapping):
    """Replace base64 reference definitions with paths to real image files."""
    written = []

    def replace(match):
        ref, fmt, blob = match.group(1), match.group(2), match.group(3)
        if ref in mapping:
            return "[%s]: %s" % (ref, mapping[ref])
        ext = EXT_FIX.get(fmt.lower(), fmt.lower())
        name = "%s-%s.%s" % (slug, slugify(ref), ext)
        path = os.path.join(IMAGES_DIR, name)
        data = base64.b64decode(re.sub(r"\s+", "", blob))
        if not os.path.exists(path) or open(path, "rb").read() != data:
            with open(path, "wb") as fh:
                fh.write(data)
            written.append(name)
        return "[%s]: images/%s" % (ref, name)

    body = DATA_URI_DEF.sub(replace, body)
    return body, written


def strip_leading_title(body):
    """Drop the `# Title` / `## date` header the editor exported, if present."""
    title = date_line = None
    lines = body.splitlines()
    i = 0
    while i < len(lines) and not lines[i].strip():
        i += 1
    if i < len(lines) and lines[i].startswith("# "):
        title = lines[i][2:].strip()
        i += 1
        while i < len(lines) and not lines[i].strip():
            i += 1
        if i < len(lines) and lines[i].startswith("## "):
            candidate = lines[i][3:].strip()
            if parse_date(candidate):
                date_line = candidate
                i += 1
        body = "\n".join(lines[i:]).lstrip("\n")
    return body, title, date_line


SCENE_BREAK = re.compile(r"^[ \t]*(?:\\?\*[ \t]*){3,}$", re.M)


def mark_scene_breaks(body):
    return SCENE_BREAK.sub('<p class="scene-break">* * *</p>', body)


# --------------------------------------------------------------------------
# html postprocessing
# --------------------------------------------------------------------------

LONE_IMAGE = re.compile(r"<p>\s*(<img\b[^>]*/?>)\s*</p>")
ALT_ATTR = re.compile(r'\balt="([^"]*)"')
LINK = re.compile(r'<a\s+href="(https?://[^"]+)"')


def wrap_images_in_figures(html_text):
    def replace(match):
        tag = match.group(1)
        alt = ALT_ATTR.search(tag)
        caption = alt.group(1).strip() if alt else ""
        if caption:
            return "<figure>%s<figcaption>%s</figcaption></figure>" % (tag, caption)
        return "<figure>%s</figure>" % tag

    return LONE_IMAGE.sub(replace, html_text)


def open_external_links(html_text):
    return LINK.sub(
        lambda m: '<a href="%s" target="_blank" rel="noopener"' % m.group(1),
        html_text,
    )


def indent(text, pad):
    return "\n".join(pad + line if line.strip() else line for line in text.splitlines())


# --------------------------------------------------------------------------
# build
# --------------------------------------------------------------------------

def build_post(md_path, template):
    with open(md_path, encoding="utf-8") as fh:
        source = fh.read()

    meta, body = parse_front_matter(source)
    if truthy(meta.get("draft", "")):
        print("  skipped (draft): %s" % os.path.basename(md_path))
        return None

    body, doc_title, doc_date = strip_leading_title(body)

    title = meta.get("title") or doc_title
    if not title:
        sys.exit("%s: no title in front matter and no leading '# heading'" % md_path)

    raw_date = meta.get("date") or doc_date
    published = parse_date(raw_date) if raw_date else None
    if published is None:
        published = date.fromtimestamp(os.path.getmtime(md_path))
        print("  warning: no date found, using file date for %s" % os.path.basename(md_path))

    slug = meta.get("slug") or slugify(meta.get("short_title") or title)
    output = meta.get("output") or "blog-%s.html" % slug

    images = meta.get("images") if isinstance(meta.get("images"), dict) else {}
    body, written = extract_images(body, slug, images)
    for name in written:
        print("  wrote images/%s" % name)

    body = mark_scene_breaks(body)
    rendered = markdown.markdown(
        body,
        extensions=["extra", "smarty", "sane_lists"],
        output_format="html5",
    )
    rendered = open_external_links(wrap_images_in_figures(rendered))

    hero = ""
    if meta.get("hero"):
        hero = '\n\t\t\t\t\t<img src="%s" alt="%s" class="post-hero">\n' % (
            meta["hero"],
            html.escape(meta.get("hero_alt", ""), quote=True),
        )

    card_image = meta.get("card_image") or meta.get("hero") or first_image(rendered)
    description = meta.get("description") or first_sentence(rendered)

    page = template
    for key, value in {
        "{{TITLE}}": html.escape(title, quote=True),
        "{{DESCRIPTION}}": html.escape(description, quote=True),
        "{{KEYWORDS}}": html.escape(
            meta.get("keywords", "Agatha Duzan blog, AI safety, AI governance"), quote=True
        ),
        "{{DATE_DISPLAY}}": published.strftime("%d.%m.%Y"),
        "{{CANONICAL_URL}}": "%s/%s" % (SITE_URL, output),
        "{{OG_IMAGE}}": "%s/%s" % (SITE_URL, card_image) if card_image else "",
        "{{HERO}}": hero,
        "{{BODY}}": indent(rendered, "\t\t\t\t\t\t"),
    }.items():
        page = page.replace(key, value)

    with open(os.path.join(ROOT, output), "w", encoding="utf-8") as fh:
        fh.write(page)
    print("  built %s" % output)

    return {
        "url": output,
        "title": meta.get("short_title") or title,
        "date": published,
        "image": card_image or "",
        "blurb": meta.get("blurb", ""),
    }


FIRST_IMG = re.compile(r'<img\b[^>]*\bsrc="([^"]+)"')
TAGS = re.compile(r"<[^>]+>")


def first_image(html_text):
    match = FIRST_IMG.search(html_text)
    return match.group(1) if match else ""


def first_sentence(html_text):
    text = html.unescape(TAGS.sub("", html_text)).strip()
    text = re.sub(r"\s+", " ", text)
    match = re.match(r"(.{40,200}?[.!?])\s", text)
    return match.group(1) if match else text[:160]


def render_list(posts):
    """One clickable row per post: date, title, and an optional blurb."""
    rows = []
    for post in sorted(posts, key=lambda p: p["date"], reverse=True):
        blurb = (
            '\n\t\t\t\t\t\t\t\t<span class="post-list-blurb">%s</span>'
            % html.escape(post["blurb"])
            if post["blurb"]
            else ""
        )
        rows.append(
            "\t\t\t\t\t\t<li>\n"
            '\t\t\t\t\t\t\t<a href="%s">\n'
            '\t\t\t\t\t\t\t\t<span class="post-list-date">%s</span>\n'
            "\t\t\t\t\t\t\t\t<span class=\"post-list-text\">\n"
            '\t\t\t\t\t\t\t\t\t<span class="post-list-title">%s</span>%s\n'
            "\t\t\t\t\t\t\t\t</span>\n"
            "\t\t\t\t\t\t\t</a>\n"
            "\t\t\t\t\t\t</li>"
            % (
                post["url"],
                post["date"].strftime("%d.%m.%Y"),
                html.escape(post["title"]),
                blurb.replace("\t" * 8, "\t" * 9),
            )
        )
    return "\n".join(rows)


def update_index(posts):
    with open(INDEX, encoding="utf-8") as fh:
        page = fh.read()
    if POSTS_START not in page or POSTS_END not in page:
        print("  note: blog.html has no BLOG_POSTS markers, leaving it alone")
        return
    start = page.index(POSTS_START) + len(POSTS_START)
    end = page.index(POSTS_END)
    updated = page[:start] + "\n" + render_list(posts) + "\n\t\t\t\t\t\t" + page[end:]
    if updated != page:
        with open(INDEX, "w", encoding="utf-8") as fh:
            fh.write(updated)
        print("  updated blog.html (%d post%s)" % (len(posts), "" if len(posts) == 1 else "s"))
    else:
        print("  blog.html already up to date")


def main(argv):
    with open(TEMPLATE, encoding="utf-8") as fh:
        template = fh.read()

    if argv:
        paths = [os.path.abspath(p) for p in argv]
        rebuild_index = False
    else:
        paths = sorted(
            os.path.join(POSTS_DIR, name)
            for name in os.listdir(POSTS_DIR)
            if name.endswith(".md") and not name.startswith("_")
        )
        rebuild_index = True

    if not paths:
        print("No markdown posts found in blogposts/")
        return

    posts = []
    for path in paths:
        print(os.path.basename(path))
        post = build_post(path, template)
        if post:
            posts.append(post)

    if rebuild_index and posts:
        update_index(posts)


if __name__ == "__main__":
    main(sys.argv[1:])
